#!/usr/bin/env bash
# Assemble the repo-root .env for the AWS demo from:
#   - the block infra/aws/bootstrap.sh printed (pass its log file)
#   - .env.runtime  (AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY of the scoped user)
#   - a fresh IDENTITY_HASH_SALT unless one is already in .env
# The previous .env is kept as .env.offline.
#   infra/aws/assemble-env.sh /tmp/vdc-bootstrap.log
set -euo pipefail
LOG="${1:?path to the bootstrap log}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"
[ -s .env.runtime ] || { echo ".env.runtime missing (create the runtime IAM user first)" >&2; exit 1; }
grep -q '^DATABASE_URL=' "$LOG" || { echo "no DATABASE_URL in $LOG; did bootstrap finish?" >&2; exit 1; }

[ -f .env ] && [ ! -f .env.offline ] && cp .env .env.offline
SALT=$(grep -s '^IDENTITY_HASH_SALT=' .env | cut -d= -f2- | grep -v 'local-dev' || true)
[ -n "$SALT" ] || SALT=$(openssl rand -hex 32)

{
  echo "# Generated by infra/aws/assemble-env.sh on $(date -u +%FT%TZ). Do not commit."
  sed -n '/^AWS_REGION=/,/^DATABASE_URL=/p' "$LOG"
  cat .env.runtime
  echo "PG_CA_CERT_PATH=$ROOT/infra/aws/rds-global-bundle.pem"
  echo "S3_KMS_KEY_ID="
  echo "IDENTITY_HASH_SALT=$SALT"
  echo "SIMILAR_MIN_SIMILARITY=0.70"
  echo "DAILY_TOKEN_BUDGET=400000"
  echo "RULES_SERVICE_URL=http://localhost:8081"
  echo "EXTRACTOR_URL=http://localhost:8000"
} > .env.new
mv .env.new .env
chmod 600 .env
echo "wrote .env ($(grep -c . .env) lines); offline values kept in .env.offline"
grep -E '^(AI_PROVIDER|ANTHROPIC_MODEL|ANTHROPIC_CLASSIFY_MODEL|AGENT_MODEL|EMBEDDING_MODEL|S3_BUCKET)=' .env
echo "DATABASE_URL=postgresql://app:***@$(grep '^DATABASE_URL=' .env | sed -E 's#.*@##')"
